@host = http://localhost:4566/restapis/3sa1tqkv5u/local/_user_request_
@user_email = test@gmail.com

### Create account
POST {{host}}/user/create
Content-Type: application/json

{
  "email": "{{user_email}}",
  "password": "12345678"
}

### Get account
GET {{host}}/user/search?email={{user_email}}
Accept: application/json

### Update account
PUT {{host}}/user/update
Content-Type: application/json

{
  "email": "{{user_email}}",
  "password": "87654321",
  "company_name": "coplayer business"
}

### Delete account
DELETE {{host}}/user/delete
Content-Type: application/json

{
  "email": "{{user_email}}"
}
